### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by Sarveshgithub** [rahulmalhotra/HTTPCalloutFramework#1]
1. It seems like the basic version, no handling outh2.0 token-based authorization.
2. Needs to be implemented in a better way like separate object means OOPs concept like Interface, etc.
3. Must have a capability to use Naming Credential (to secure username and password)

Best
-Sarvesh.

**Comment by rahulmalhotra** [comment]
Hey Sarvesh,

For 1. every system has it's own way to implement oauth 2.0 so we cannot write a generalized code for that and providing interface for the same is not that good option as the best way to implement that is using named credentials. Point 3. is also covered in this as the framework supports named credentials. Please let me know the scenario if it didn't work out for you.

Regarding point 2. the classes provided in this framework are generalized and ready for use, so there is no requirement of creating interfaces to override anything. However, if you still have any specific idea of improvement please explain in more detail.
